create table if not exists public.products (
  id bigint generated by default as identity primary key,
  status text not null
    check (status in ('draft', 'published', 'archived')),
  title text not null
    check (char_length(btrim(title)) between 1 and 160),
  category text not null
    check (char_length(btrim(category)) between 1 and 80),
  tag text
    check (tag is null or char_length(btrim(tag)) between 1 and 80),
  featured boolean not null default false,
  image_path text not null
    check (char_length(btrim(image_path)) between 1 and 500),
  original_price_cents integer not null
    check (original_price_cents > 0),
  price_cents integer not null
    check (price_cents > 0),
  description text not null
    check (char_length(btrim(description)) between 1 and 5000),
  notice text
    check (notice is null or char_length(btrim(notice)) between 1 and 500),
  colors jsonb not null default '[]'::jsonb
    check (jsonb_typeof(colors) = 'array'),
  highlights jsonb not null default '[]'::jsonb
    check (jsonb_typeof(highlights) = 'array'),
  details jsonb not null default '[]'::jsonb
    check (jsonb_typeof(details) = 'array'),
  sections jsonb not null default '[]'::jsonb
    check (jsonb_typeof(sections) = 'array'),
  shipping_weight_kg numeric(10,3) not null
    check (shipping_weight_kg > 0),
  shipping_length_cm numeric(10,2) not null
    check (shipping_length_cm > 0),
  shipping_width_cm numeric(10,2) not null
    check (shipping_width_cm > 0),
  shipping_height_cm numeric(10,2) not null
    check (shipping_height_cm > 0),
  display_order integer not null default 0
    check (display_order between 0 and 1000000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_products_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row
execute function public.set_products_updated_at();

alter table public.products enable row level security;

revoke all on table public.products from public, anon, authenticated;

insert into public.products (
  id,
  status,
  title,
  category,
  tag,
  featured,
  image_path,
  original_price_cents,
  price_cents,
  description,
  notice,
  colors,
  highlights,
  details,
  sections,
  shipping_weight_kg,
  shipping_length_cm,
  shipping_width_cm,
  shipping_height_cm,
  display_order
)
values
  (1,
   'published',
   'Deck Commander Proxy 100 Cartas',
   'Decks',
   'Mais Vendido',
   true,
   '/products/deck-commander.png',
   15000,
   11990,
   'Deck com 100 cartas proxy personalizadas, produzido em alta qualidade para jogos casuais, testes e montagem de decks. Você escolhe as 100 cartas da sua lista.',
   'Informações importantes',
   '["Azul", "Preto"]'::jsonb,
   '["100 cartas", "Lista escolhida por você", "Produção em até 5 dias úteis"]'::jsonb,
   '[{"label":"O QUE VOCÊ RECEBE","value":"100 cartas proxy no tamanho padrão de Magic: The Gathering."},{"label":"QUALIDADE","value":"Impressão em papel fotográfico com laminação, proporcionando boa definição, cores vivas e maior durabilidade."},{"label":"VERSO","value":"Verso branco, sem arte. Recomendamos o uso de sleeves opacos."},{"label":"COMO ESCOLHER AS CARTAS","value":"Após concluir o pedido, envie sua lista pelo WhatsApp. Pode ser por Moxfield, LigaMagic ou outro formato combinado no atendimento."},{"label":"ARTES","value":"Utilizamos as artes disponíveis em nosso banco. Artes ou impressões personalizadas podem ter custo adicional, sempre informado antes da produção."}]'::jsonb,
   '[{"title":"IMPORTANTE","paragraphs":["Este produto é composto por cartas em versão proxy não oficial, destinadas a jogo casual e testes. Não são cartas oficiais de Magic: The Gathering e não devem ser utilizadas em torneios sancionados."]},{"title":"PRAZO","paragraphs":["Produção e postagem em até 5 dias úteis."]}]'::jsonb,
   0.500,
   25.00,
   19.00,
   4.00,
   1),
  (2,
   'published',
   'Deck Proxy 60 Cartas',
   'Decks',
   null,
   false,
   '/products/deck-commander.png',
   9999,
   6999,
   'Deck com 60 cartas proxy personalizadas, produzido em alta qualidade para jogos casuais, testes e montagem de decks. Você escolhe as 60 cartas da sua lista.',
   'Informações importantes',
   '[]'::jsonb,
   '["60 cartas", "Lista escolhida por você", "Produção em até 5 dias úteis"]'::jsonb,
   '[{"label":"O QUE VOCÊ RECEBE","value":"60 cartas proxy no tamanho padrão de Magic: The Gathering."},{"label":"QUALIDADE","value":"Impressão em papel fotográfico com laminação, proporcionando boa definição, cores vivas e maior durabilidade."},{"label":"VERSO","value":"Verso branco, sem arte. Recomendamos o uso de sleeves opacos."},{"label":"COMO ESCOLHER AS CARTAS","value":"Após concluir o pedido, envie sua lista pelo WhatsApp. Pode ser por Moxfield, LigaMagic ou outro formato combinado no atendimento."},{"label":"ARTES","value":"Utilizamos as artes disponíveis em nosso banco. Artes ou impressões personalizadas podem ter custo adicional, sempre informado antes da produção."}]'::jsonb,
   '[{"title":"IMPORTANTE","paragraphs":["Este produto é composto por cartas em versão proxy não oficial, destinadas a jogo casual e testes. Não são cartas oficiais de Magic: The Gathering e não devem ser utilizadas em torneios sancionados."]},{"title":"PRAZO","paragraphs":["Produção e postagem em até 5 dias úteis."]}]'::jsonb,
   0.500,
   25.00,
   19.00,
   4.00,
   2)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  greatest((select coalesce(max(id), 2) from public.products), 2),
  true
);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'product-images',
  'product-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
